FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
ENV ASPNETCORE_ENVIRONMENT=Production
ENV ASPNETCORE_URLS=http://+:5001
EXPOSE 5001

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
FROM build AS publish
RUN dotnet publish IdentityServer5.csproj -c Release -o /app

#COPY publish .
WORKDIR /app
ENTRYPOINT ["dotnet", "IdentityServer5.dll"]