# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

stages:
  - stage: Build
    displayName: Build CI
    pool:
      vmImage: ubuntu-latest
    jobs: 
     - job: Build
       displayName: Build CI
       steps:
         - task: NuGetCommand@2
           inputs:
             command: 'restore'
             restoreSolution: '**/*.sln'
             feedsToUse: 'select'
         - task: DotNetCoreCLI@2
           condition: succeeded()
           inputs:
             command: 'build'
             projects: '**/*.csproj'
             
         - task: GitTag@7
           condition: succeeded()
           inputs:
             workingdir: '$(SYSTEM.DEFAULTWORKINGDIRECTORY)'
             tagEmail: 'a.jorayev@baik.uz'
             tag: 'v1.0.$(build.buildNumber)'
        
          

